### PR TITLE
Add Use Kudos widget

### PR DESCRIPTION
**Pull request by henrahmagix**
Hi! Hope you don't mind me making this small addition (a new widget has gone live) =) Great tool!

image

### CODE REVIEW

**Review by marmadukeandbob05 — APPROVED** [review]
Thanks for the contribution!👍 Sorry about the inline CSS/badly laid out JS :-)

**Comment by henrahmagix** [comment]
All good, thanks for merging :)

**Comment by marmadukeandbob05** [comment]
Does it work on your computer? For me, only the explain widget works.

**Comment by henrahmagix** [comment]
This widget only shows for unexplained publications, so it’s like the inverse of the Explain widget. Try it with 10.5555/123456789 :)

**Comment by marmadukeandbob05** [comment]
Oh. Thanks for that. What about the resource widget? For me, that doesn't work either. Is that because there are no resources?

**Comment by henrahmagix** [comment]
Yeah, that’s the case for that particular DOI :)

**Comment by marmadukeandbob05** [comment]
I tried a few different DOIs and just came to the same conclusion :-)

**Comment by marmadukeandbob05** [comment]
Also just updated the whole UI of the tool.

**Pull request merged**
